### ISSUE TITLE
Can't deploy App Service

### ISSUE THREAD

**Issue by jimmyliao** [pablomarin/GPT-Azure-Search-Engine#11]
- Trial 1: az webapp deployment, Git Actions, Local git
==> Got azure deploy deployment conflict (code: 409)

- Trial 2: create template on portal
==> Got timeout

Test commit hash: 2c10f7b2d90cce3b6ffa795b806de84269bb0b6f

**Comment by pablomarin** [comment]
We are working on the cause of this issue. We are changing the deployment to Github Actions instead.
In the meantime run it locally or try Streamlit cloud that is free, just connect it to your github fork and you can have it deployed.
