### ISSUE TITLE
Playing with the model, interesting outcome...

### ISSUE THREAD

**Issue by raycrawford** [pablomarin/GPT-Azure-Search-Engine#14]
Playing with the Streamlit model, I was asking the recommended question "list the authors that talk about Boosting Algorithms" and I got (what I assume) is the expected response - "The authors that talk about Boosting Algorithms are Ninan Sajeeth Philip and K. Babu Joseph, and Schapire.".  However, if I start asking about dates, it doesn't return anything...  such as: "How do Ninan Sajeeth Philip papers relate to booting algorithms?" or "when did Ninan Sajeeth Philip write papers relating to booting algorithms?".

The model doesn't seem to know anything about dates.  Does this have to do with how the data model was built?

**Comment by pablomarin** [comment]
It is because on the file where those authors are mentioned, there is no more information about it.
