### ISSUE TITLE
Over resource limits on Streamlit Cloud

### ISSUE THREAD

**Issue by amitmukh** [pablomarin/GPT-Azure-Search-Engine#15]
Hey there :wave: Just wanted to let you know that [your app on Streamlit Cloud deployed from this repo](https://pablomarin-gpt-azure-search-engine-apphome-oq98mn.streamlit.app/pablomarin/gpt-azure-search-engine/main/app/Home.py) has gone over its resource limits. Access to the app is temporarily limited. Visit the app to see more details and possible solutions.

**Comment by pablomarin** [comment]
Yes, a lot of people using it and I don't want to pay more :)
