### ISSUE TITLE
Create Indexer REST API Call Fails with Data Source Auth Issue

### ISSUE THREAD

**Issue by agsanderss** [pablomarin/GPT-Azure-Search-Engine#20]
Rest API call to create indexer in 01-Load-Data-ACogSearch.ipynb with the default arxivcs container with: 

"error":{"code":"","message":"Error with data source: Credentials provided in the connection string are invalid or have expired.\\r\\nFor more information on troubleshooting connection issues to Azure Storage accounts, please see https://go.microsoft.com/fwlink/?linkid=2049388  Please adjust your data source definition in order to proceed."

Potentially a firewall issue but couldn't troubleshoot locally. SAS Token Auth also fails in Storage Explorer.

**Comment by pablomarin** [comment]
Hello,

Can you pull the changes to the repo?
The datasource connectiong string to the demo data has been updated.

Please pull again and run again
