### ISSUE TITLE
 AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by cjpark-sapcsa** [pablomarin/GPT-Azure-Search-Engine#33]
Hi All, 

Running 01-Lod-Data-AcogSearch.ipynb 

# Change these below with your own services credentials
AZURE_SEARCH_ENDPOINT = ""   <= URL of Search Service 
AZURE_SEARCH_KEY = " "              <= Keys  Manage admin keys 
COG_SERVICES_NAME = ""            <= name of search service,  e.g cog-search-xxxx
COG_SERVICES_KEY = ""                <=  cog-search-xxxx   , this is manage query keys   

I have added like the above and 
![400 false](https://github.com/pablomarin/GPT-Azure-Search-Engine/assets/60184856/76ed265e-b6d3-47d2-9f7d-063ceb080a31)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[27], line 6
      4 # pprint(json.dumps(r.json(), indent=1))
      5 print(r.status_code)
----> 6 print("Status:",r.json().get('lastResult').get('status'))
      7 print("Items Processed:",r.json().get('lastResult').get('itemsProcessed'))
      8 print(r.ok)

AttributeError: 'NoneType' object has no attribute 'get'.  anyone seen this erro ?

**Comment by pablomarin** [comment]
This happens when you run this cell inmediately after the prior cell and when the indexer has not process any file yet. Give it a minute or so , so that the indexer starts processing and you will see results.
