### ISSUE TITLE
Cog Search Vector Capability to replace in-memory FAISS DB

### ISSUE THREAD

**Issue by pablomarin** [pablomarin/GPT-Azure-Search-Engine#34]

**Comment by jason-theodorakopoulos** [comment]
Hello @pablomarin.
Is there an ETA on having vector search capability on top of Azure Cog search?
Also, what is the planned solution - is it to first vectorize all chunks of the documents and store them in the Azure cog search vector db, or, to just vectorize the top K results returned by the Azure cog search? (IMO the first approach would yield better results)

**Comment by pablomarin** [comment]
This was release a few weeks ago. Please check new notebooks.
