### ISSUE TITLE
Missing credentials.py

### ISSUE THREAD

**Issue by fclaudiopalmeira** [pablomarin/GPT-Azure-Search-Engine#43]
On 01-Load-Data-ACogSearch.ypynb it mentions a credentials.py on the directory app:
"Create a data source
 You should already have a blob container that contains the sample data, see app/credentials.py"
That file doesn't seem to be present anywhere.

**Comment by pablomarin** [comment]
Good catch, this is an old comment left behind. 
app/credentials.py doesn't exists anymore
