### ISSUE TITLE
Backend Webapp not able to spinup

### ISSUE THREAD

**Issue by shivanand-satigoudar** [pablomarin/GPT-Azure-Search-Engine#45]
While deploying earlier backend webapp was failing with container crash issue being exception: ModuleNotFoundError: No Module named ‘aiohttp’. When I redeployed again with python 3.10 this issue is resolved.

As of now container is not crashing and getting following warning: 

File "/tmp/8db6d8a271372eb/antenv/lib/python3.10/site-packages/botbuilder/core/integration/aiohttp_channel_service_exception_middleware.py", line 20, in aiohttp_error_middleware
response = await handler(request)
 File "/tmp/8db6d8a271372eb/antenv/lib/python3.10/site-packages/aiohttp/web_urldispatcher.py", line 931, in _handle
raise self._http_exception
aiohttp.web_exceptions.HTTPNotFound: Not Found
Task exception was never retrieved
future:  exception=KeyError('access_token')>. These exceptions are coming from application. Any help in this regard would be much apprciated..Thanks:-)

**Comment by pablomarin** [comment]
Yes. We are aware of that warning . It doesn't affect the functioning of the bot , however we are investigating on how to solve the warning .
Thank you for reporting
