### ISSUE TITLE
I can't find a place to accept the Responsible AI terms，Can someone please help me out there？

### ISSUE THREAD

**Issue by lb1223** [pablomarin/GPT-Azure-Search-Engine#48]

**Comment by pablomarin** [comment]
Create manually in the azure portal a Cognitive Multi-Service account

**Comment by lb1223** [comment]
thank you .It works.
 However, in the local installation, I keep reporting errors here. It seems that there is a problem with filling in credentials.env, but I really can’t find where the error is. Can you have a screenshot to explain which endpoint is the next part? thanks again
