### ISSUE TITLE
£500+ bill in a day just to run the notebook examples

### ISSUE THREAD

**Issue by morriswong** [pablomarin/GPT-Azure-Search-Engine#53]
I followed the template the deploy all the service need to test this demo out, and got this bill the next morning, is this normal?

![image](https://github.com/pablomarin/GPT-Azure-Search-Engine/assets/8597011/8e0f30db-44bc-4d2a-a271-57300eed3661)

**Comment by pablomarin** [comment]
Yes, very normal. It costs money to index and do AI enrichment on all the 10k PDFs and 90k Covid articles
