### ISSUE TITLE
Validation failed. View error details

### ISSUE THREAD

**Issue by JC324-cam** [pablomarin/GPT-Azure-Search-Engine#59]
Hi,

I tried to deploy with the custom template to create all the Azure Infrastructure needed to run the Notebooks (Azure Cognitive Search, Cognitive Services, SQL Database, CosmosDB, Bing Search API), but I got the following error message.

"InvalidTemplateDeployment: The template deployment 'MicrosoftTemplate' is not valid according to the validation procedure. The tracking id is '2d765e2c-4e79-4062-a78a-c26e02d13xxx. See inner errors for details.

Does anyone have the same problem before? Thanks

**Comment by pablomarin** [comment]
Not able to replicate. Closing.
