### ISSUE TITLE
Citations for sites indexed via CSV

### ISSUE THREAD

**Issue by kylgrn** [pablomarin/GPT-Azure-Search-Engine#62]
Hi Pablo, can you provide any guidance around how you configured the web app to structure and citate the URL for the sites in the ncbi data set? Also, if you have any guidance on how you built the CSV from the ncbi website. Looking to do something similar for ServiceNow KB articles. Any input would be greatly appreciated! Awesome project.

**Comment by pablomarin** [comment]
Kylgrn, I didn't build the CSV, I just truncated a large file made by the Cord19 repository.
