### ISSUE TITLE
HTTP status code NotFound at Backend Bot service

### ISSUE THREAD

**Issue by HappyGroupHub** [pablomarin/GPT-Azure-Search-Engine#79]
I'm trying to deploy my backend and fronted webiste to Azure App Services and Bot Service, however, the frontend website was successfully deployed but the backend doesn't. The bakend is not wokring with error `There was an error sending this message to your bot: HTTP status code NotFound`, it's both not working with Web Chat and Direct Line.
I've passed all the notebook files successfully but troubled while deploying to App Service, please help and thanks.
![image](https://github.com/pablomarin/GPT-Azure-Search-Engine/assets/43276256/3e4b7dfd-813e-4e90-b6bf-a11c39a770ae)

**Comment by pablomarin** [comment]
This sounds like you have a bad app client ID or bot secret.

Make sure that your service principal (app registration) is multi-tenant
and that you have copied correctly the client ID and the client secret
value

**Comment by HappyGroupHub** [comment]
Just tried re-creating the backend App service and the Bot service, but the same problem still exists. Any other potential issues?

**Comment by pablomarin** [comment]
Make sure the bot service is working in the Test Erb Chat feature on the
azure portal .

**Comment by HappyGroupHub** [comment]
No, the Test in Web Chat feature didn't work as well.
I've double checked that my App Cliet ID and secret is set to multi-tenant.
I think the problem here is there's a commuication error while backend app service connecting to Bot Service, since both Test in Web Chat eroor was as same as the error appeared using Direct LINE from fronted website. As below.
![image](https://github.com/pablomarin/GPT-Azure-Search-Engine/assets/43276256/2b2065ce-0d90-4142-9703-b6163fd1671f)
![image](https://github.com/pablomarin/GPT-Azure-Search-Engine/assets/43276256/f7257b38-dd3f-44e2-89a9-b39f7c89fbd4)

**Comment by pablomarin** [comment]
I just did this code with two customers this week and is working as
expected. You are doing something that is causing the webapp not talking to
the bot service , probably a copy paste error somewhere of a variable name
or something

**Comment by HappyGroupHub** [comment]
I see. Just check that all the credentials are correct.
Still investigating on this issue.
Will post here if I find any update.

**Comment by HappyGroupHub** [comment]
Should there be anything showing in「Log stream」 in Backend Web App while I'm trying to dircetly access the backend endpoint? Just jump into the Log stream of the backend app service, found that the app seems initalize as well, but there won't be any logs if I ty to access the endpoint.
![image](https://github.com/pablomarin/GPT-Azure-Search-Engine/assets/43276256/16ce7563-1f9a-4402-8f86-8cf243aee39e)
![image](https://github.com/pablomarin/GPT-Azure-Search-Engine/assets/43276256/a22597e2-a5c6-4d81-82d9-b9484775fe75)

The backend endpoint should be '{backendAppDomain}/api/messages' right? Which should be as same as the value written on Bot service > Configuration > Messaging Endpoint. If I directly access this url on web, It'll shows up `405: Method Not Allowed` right?

**Comment by HappyGroupHub** [comment]
Just found some errors thrown in Log stream at backend web app, but got no idea about what "access_token" is missed. Is this normal?
![image](https://github.com/pablomarin/GPT-Azure-Search-Engine/assets/43276256/5fd7421d-db1d-4f75-a06c-719b963fe9a9)

**Comment by HappyGroupHub** [comment]
This problem has been solved. A dumb input bug found.
After the third check, I found that the App registration secrect has been misplaced with "Secret ID", which is not correct. The "Secret Value" will be the correct input for AppPassword.
